// generated by scripts/generate-bcdice-i18n.mjs — do not edit
import Amadeus_ja_jp from 'bcdice/lib/bcdice/i18n/Amadeus.ja_jp.json';
import Amadeus_ko_kr from 'bcdice/lib/bcdice/i18n/Amadeus.ko_kr.json';
import Arianrhod_ja_jp from 'bcdice/lib/bcdice/i18n/Arianrhod.ja_jp.json';
import Arianrhod_ko_kr from 'bcdice/lib/bcdice/i18n/Arianrhod.ko_kr.json';
import BeginningIdol_ja_jp from 'bcdice/lib/bcdice/i18n/BeginningIdol.ja_jp.json';
import BeginningIdol_ko_kr from 'bcdice/lib/bcdice/i18n/BeginningIdol.ko_kr.json';
import Cthulhu_en_us from 'bcdice/lib/bcdice/i18n/Cthulhu.en_us.json';
import Cthulhu_ja_jp from 'bcdice/lib/bcdice/i18n/Cthulhu.ja_jp.json';
import Cthulhu_ko_kr from 'bcdice/lib/bcdice/i18n/Cthulhu.ko_kr.json';
import Cthulhu_zh_hans from 'bcdice/lib/bcdice/i18n/Cthulhu.zh_hans.json';
import Cthulhu_zh_hant from 'bcdice/lib/bcdice/i18n/Cthulhu.zh_hant.json';
import CyberpunkRed_ja_jp from 'bcdice/lib/bcdice/i18n/CyberpunkRed.ja_jp.json';
import CyberpunkRed_ko_kr from 'bcdice/lib/bcdice/i18n/CyberpunkRed.ko_kr.json';
import DetatokoSaga_ja_jp from 'bcdice/lib/bcdice/i18n/DetatokoSaga.ja_jp.json';
import DetatokoSaga_ko_kr from 'bcdice/lib/bcdice/i18n/DetatokoSaga.ko_kr.json';
import DoubleCross_ja_jp from 'bcdice/lib/bcdice/i18n/DoubleCross.ja_jp.json';
import DoubleCross_ko_kr from 'bcdice/lib/bcdice/i18n/DoubleCross.ko_kr.json';
import Dracurouge_ja_jp from 'bcdice/lib/bcdice/i18n/Dracurouge.ja_jp.json';
import Dracurouge_ko_kr from 'bcdice/lib/bcdice/i18n/Dracurouge.ko_kr.json';
import Emoklore_ja_jp from 'bcdice/lib/bcdice/i18n/Emoklore.ja_jp.json';
import Emoklore_ko_kr from 'bcdice/lib/bcdice/i18n/Emoklore.ko_kr.json';
import Fiasco_ja_jp from 'bcdice/lib/bcdice/i18n/Fiasco.ja_jp.json';
import Fiasco_ko_kr from 'bcdice/lib/bcdice/i18n/Fiasco.ko_kr.json';
import FinalFantasyXIV_en_us from 'bcdice/lib/bcdice/i18n/FinalFantasyXIV.en_us.json';
import FinalFantasyXIV_ja_jp from 'bcdice/lib/bcdice/i18n/FinalFantasyXIV.ja_jp.json';
import FutariSousa_ja_jp from 'bcdice/lib/bcdice/i18n/FutariSousa.ja_jp.json';
import FutariSousa_ko_kr from 'bcdice/lib/bcdice/i18n/FutariSousa.ko_kr.json';
import Insane_ja_jp from 'bcdice/lib/bcdice/i18n/Insane.ja_jp.json';
import Insane_ko_kr from 'bcdice/lib/bcdice/i18n/Insane.ko_kr.json';
import Kamigakari_ja_jp from 'bcdice/lib/bcdice/i18n/Kamigakari.ja_jp.json';
import Kamigakari_ko_kr from 'bcdice/lib/bcdice/i18n/Kamigakari.ko_kr.json';
import KillDeathBusiness_ja_jp from 'bcdice/lib/bcdice/i18n/KillDeathBusiness.ja_jp.json';
import KillDeathBusiness_ko_kr from 'bcdice/lib/bcdice/i18n/KillDeathBusiness.ko_kr.json';
import KizunaBullet_ja_jp from 'bcdice/lib/bcdice/i18n/KizunaBullet.ja_jp.json';
import LogHorizon_ja_jp from 'bcdice/lib/bcdice/i18n/LogHorizon.ja_jp.json';
import LogHorizon_ko_kr from 'bcdice/lib/bcdice/i18n/LogHorizon.ko_kr.json';
import MagicaLogia_ja_jp from 'bcdice/lib/bcdice/i18n/MagicaLogia.ja_jp.json';
import MagicaLogia_ko_kr from 'bcdice/lib/bcdice/i18n/MagicaLogia.ko_kr.json';
import MagicaLogia_zh_hans from 'bcdice/lib/bcdice/i18n/MagicaLogia.zh_hans.json';
import MonotoneMuseum_ja_jp from 'bcdice/lib/bcdice/i18n/MonotoneMuseum.ja_jp.json';
import MonotoneMuseum_ko_kr from 'bcdice/lib/bcdice/i18n/MonotoneMuseum.ko_kr.json';
import Nechronica_ja_jp from 'bcdice/lib/bcdice/i18n/Nechronica.ja_jp.json';
import Nechronica_ko_kr from 'bcdice/lib/bcdice/i18n/Nechronica.ko_kr.json';
import NinjaSlayer2_ja_jp from 'bcdice/lib/bcdice/i18n/NinjaSlayer2.ja_jp.json';
import SkynautsBouken_ja_jp from 'bcdice/lib/bcdice/i18n/SkynautsBouken.ja_jp.json';
import SkynautsBouken_ko_kr from 'bcdice/lib/bcdice/i18n/SkynautsBouken.ko_kr.json';
import StellarKnights_ja_jp from 'bcdice/lib/bcdice/i18n/StellarKnights.ja_jp.json';
import StellarKnights_ko_kr from 'bcdice/lib/bcdice/i18n/StellarKnights.ko_kr.json';
import StratoShout_ja_jp from 'bcdice/lib/bcdice/i18n/StratoShout.ja_jp.json';
import StratoShout_ko_kr from 'bcdice/lib/bcdice/i18n/StratoShout.ko_kr.json';
import SwordWorld_ja_jp from 'bcdice/lib/bcdice/i18n/SwordWorld.ja_jp.json';
import SwordWorld_zh_hans from 'bcdice/lib/bcdice/i18n/SwordWorld.zh_hans.json';
import SwordWorld2_0_ja_jp from 'bcdice/lib/bcdice/i18n/SwordWorld2_0.ja_jp.json';
import SwordWorld2_0_zh_hans from 'bcdice/lib/bcdice/i18n/SwordWorld2_0.zh_hans.json';
import SwordWorld2_5_ja_jp from 'bcdice/lib/bcdice/i18n/SwordWorld2_5.ja_jp.json';
import SwordWorld2_5_zh_hans from 'bcdice/lib/bcdice/i18n/SwordWorld2_5.zh_hans.json';
import TensaiGunshiNiNaro_ja_jp from 'bcdice/lib/bcdice/i18n/TensaiGunshiNiNaro.ja_jp.json';
import UnsungDuet_ja_jp from 'bcdice/lib/bcdice/i18n/UnsungDuet.ja_jp.json';
import UnsungDuet_ko_kr from 'bcdice/lib/bcdice/i18n/UnsungDuet.ko_kr.json';

export const BCDICE_I18N_TRANSLATIONS: readonly object[] = [
  Amadeus_ja_jp,
  Amadeus_ko_kr,
  Arianrhod_ja_jp,
  Arianrhod_ko_kr,
  BeginningIdol_ja_jp,
  BeginningIdol_ko_kr,
  Cthulhu_en_us,
  Cthulhu_ja_jp,
  Cthulhu_ko_kr,
  Cthulhu_zh_hans,
  Cthulhu_zh_hant,
  CyberpunkRed_ja_jp,
  CyberpunkRed_ko_kr,
  DetatokoSaga_ja_jp,
  DetatokoSaga_ko_kr,
  DoubleCross_ja_jp,
  DoubleCross_ko_kr,
  Dracurouge_ja_jp,
  Dracurouge_ko_kr,
  Emoklore_ja_jp,
  Emoklore_ko_kr,
  Fiasco_ja_jp,
  Fiasco_ko_kr,
  FinalFantasyXIV_en_us,
  FinalFantasyXIV_ja_jp,
  FutariSousa_ja_jp,
  FutariSousa_ko_kr,
  Insane_ja_jp,
  Insane_ko_kr,
  Kamigakari_ja_jp,
  Kamigakari_ko_kr,
  KillDeathBusiness_ja_jp,
  KillDeathBusiness_ko_kr,
  KizunaBullet_ja_jp,
  LogHorizon_ja_jp,
  LogHorizon_ko_kr,
  MagicaLogia_ja_jp,
  MagicaLogia_ko_kr,
  MagicaLogia_zh_hans,
  MonotoneMuseum_ja_jp,
  MonotoneMuseum_ko_kr,
  Nechronica_ja_jp,
  Nechronica_ko_kr,
  NinjaSlayer2_ja_jp,
  SkynautsBouken_ja_jp,
  SkynautsBouken_ko_kr,
  StellarKnights_ja_jp,
  StellarKnights_ko_kr,
  StratoShout_ja_jp,
  StratoShout_ko_kr,
  SwordWorld_ja_jp,
  SwordWorld_zh_hans,
  SwordWorld2_0_ja_jp,
  SwordWorld2_0_zh_hans,
  SwordWorld2_5_ja_jp,
  SwordWorld2_5_zh_hans,
  TensaiGunshiNiNaro_ja_jp,
  UnsungDuet_ja_jp,
  UnsungDuet_ko_kr,
];
