// generated by scripts/generate-bcdice-i18n.mjs — do not edit
import Airgetlamh_ja_jp from 'bcdice/lib/bcdice/i18n/Airgetlamh.ja_jp.json';
import Airgetlamh_ko_kr from 'bcdice/lib/bcdice/i18n/Airgetlamh.ko_kr.json';
import Alsetto_ja_jp from 'bcdice/lib/bcdice/i18n/Alsetto.ja_jp.json';
import Alsetto_ko_kr from 'bcdice/lib/bcdice/i18n/Alsetto.ko_kr.json';
import Amadeus_ja_jp from 'bcdice/lib/bcdice/i18n/Amadeus.ja_jp.json';
import Amadeus_ko_kr from 'bcdice/lib/bcdice/i18n/Amadeus.ko_kr.json';
import AnimaAnimus_ja_jp from 'bcdice/lib/bcdice/i18n/AnimaAnimus.ja_jp.json';
import AnimaAnimus_ko_kr from 'bcdice/lib/bcdice/i18n/AnimaAnimus.ko_kr.json';
import Arianrhod_ja_jp from 'bcdice/lib/bcdice/i18n/Arianrhod.ja_jp.json';
import Arianrhod_ko_kr from 'bcdice/lib/bcdice/i18n/Arianrhod.ko_kr.json';
import BeginningIdol_ja_jp from 'bcdice/lib/bcdice/i18n/BeginningIdol.ja_jp.json';
import BeginningIdol_ko_kr from 'bcdice/lib/bcdice/i18n/BeginningIdol.ko_kr.json';
import BlackJacket_ja_jp from 'bcdice/lib/bcdice/i18n/BlackJacket.ja_jp.json';
import BlackJacket_ko_kr from 'bcdice/lib/bcdice/i18n/BlackJacket.ko_kr.json';
import Bloodorium_ja_jp from 'bcdice/lib/bcdice/i18n/Bloodorium.ja_jp.json';
import Bloodorium_ko_kr from 'bcdice/lib/bcdice/i18n/Bloodorium.ko_kr.json';
import Cthulhu_en_us from 'bcdice/lib/bcdice/i18n/Cthulhu.en_us.json';
import Cthulhu_ja_jp from 'bcdice/lib/bcdice/i18n/Cthulhu.ja_jp.json';
import Cthulhu_ko_kr from 'bcdice/lib/bcdice/i18n/Cthulhu.ko_kr.json';
import Cthulhu_zh_hans from 'bcdice/lib/bcdice/i18n/Cthulhu.zh_hans.json';
import Cthulhu_zh_hant from 'bcdice/lib/bcdice/i18n/Cthulhu.zh_hant.json';
import CyberpunkRed_ja_jp from 'bcdice/lib/bcdice/i18n/CyberpunkRed.ja_jp.json';
import CyberpunkRed_ko_kr from 'bcdice/lib/bcdice/i18n/CyberpunkRed.ko_kr.json';
import DetatokoSaga_ja_jp from 'bcdice/lib/bcdice/i18n/DetatokoSaga.ja_jp.json';
import DetatokoSaga_ko_kr from 'bcdice/lib/bcdice/i18n/DetatokoSaga.ko_kr.json';
import DoubleCross_ja_jp from 'bcdice/lib/bcdice/i18n/DoubleCross.ja_jp.json';
import DoubleCross_ko_kr from 'bcdice/lib/bcdice/i18n/DoubleCross.ko_kr.json';
import Dracurouge_ja_jp from 'bcdice/lib/bcdice/i18n/Dracurouge.ja_jp.json';
import Dracurouge_ko_kr from 'bcdice/lib/bcdice/i18n/Dracurouge.ko_kr.json';
import Emoklore_ja_jp from 'bcdice/lib/bcdice/i18n/Emoklore.ja_jp.json';
import Emoklore_ko_kr from 'bcdice/lib/bcdice/i18n/Emoklore.ko_kr.json';
import Fiasco_ja_jp from 'bcdice/lib/bcdice/i18n/Fiasco.ja_jp.json';
import Fiasco_ko_kr from 'bcdice/lib/bcdice/i18n/Fiasco.ko_kr.json';
import FinalFantasyXIV_en_us from 'bcdice/lib/bcdice/i18n/FinalFantasyXIV.en_us.json';
import FinalFantasyXIV_ja_jp from 'bcdice/lib/bcdice/i18n/FinalFantasyXIV.ja_jp.json';
import FutariSousa_ja_jp from 'bcdice/lib/bcdice/i18n/FutariSousa.ja_jp.json';
import FutariSousa_ko_kr from 'bcdice/lib/bcdice/i18n/FutariSousa.ko_kr.json';
import HatsuneMiku_ja_jp from 'bcdice/lib/bcdice/i18n/HatsuneMiku.ja_jp.json';
import HatsuneMiku_ko_kr from 'bcdice/lib/bcdice/i18n/HatsuneMiku.ko_kr.json';
import Insane_ja_jp from 'bcdice/lib/bcdice/i18n/Insane.ja_jp.json';
import Insane_ko_kr from 'bcdice/lib/bcdice/i18n/Insane.ko_kr.json';
import Irisbane_ja_jp from 'bcdice/lib/bcdice/i18n/Irisbane.ja_jp.json';
import Irisbane_ko_kr from 'bcdice/lib/bcdice/i18n/Irisbane.ko_kr.json';
import JuinKansen_ja_jp from 'bcdice/lib/bcdice/i18n/JuinKansen.ja_jp.json';
import JuinKansen_ko_kr from 'bcdice/lib/bcdice/i18n/JuinKansen.ko_kr.json';
import Kamigakari_ja_jp from 'bcdice/lib/bcdice/i18n/Kamigakari.ja_jp.json';
import Kamigakari_ko_kr from 'bcdice/lib/bcdice/i18n/Kamigakari.ko_kr.json';
import KemonoNoMori_ja_jp from 'bcdice/lib/bcdice/i18n/KemonoNoMori.ja_jp.json';
import KemonoNoMori_ko_kr from 'bcdice/lib/bcdice/i18n/KemonoNoMori.ko_kr.json';
import KillDeathBusiness_ja_jp from 'bcdice/lib/bcdice/i18n/KillDeathBusiness.ja_jp.json';
import KillDeathBusiness_ko_kr from 'bcdice/lib/bcdice/i18n/KillDeathBusiness.ko_kr.json';
import KizunaBullet_ja_jp from 'bcdice/lib/bcdice/i18n/KizunaBullet.ja_jp.json';
import KizunaBullet_ko_kr from 'bcdice/lib/bcdice/i18n/KizunaBullet.ko_kr.json';
import LogHorizon_ja_jp from 'bcdice/lib/bcdice/i18n/LogHorizon.ja_jp.json';
import LogHorizon_ko_kr from 'bcdice/lib/bcdice/i18n/LogHorizon.ko_kr.json';
import MagicaLogia_ja_jp from 'bcdice/lib/bcdice/i18n/MagicaLogia.ja_jp.json';
import MagicaLogia_ko_kr from 'bcdice/lib/bcdice/i18n/MagicaLogia.ko_kr.json';
import MagicaLogia_zh_hans from 'bcdice/lib/bcdice/i18n/MagicaLogia.zh_hans.json';
import MagicPunk_ja_jp from 'bcdice/lib/bcdice/i18n/MagicPunk.ja_jp.json';
import MagicPunk_ko_kr from 'bcdice/lib/bcdice/i18n/MagicPunk.ko_kr.json';
import MonotoneMuseum_ja_jp from 'bcdice/lib/bcdice/i18n/MonotoneMuseum.ja_jp.json';
import MonotoneMuseum_ko_kr from 'bcdice/lib/bcdice/i18n/MonotoneMuseum.ko_kr.json';
import MorkBorg_ja_jp from 'bcdice/lib/bcdice/i18n/MorkBorg.ja_jp.json';
import MorkBorg_ko_kr from 'bcdice/lib/bcdice/i18n/MorkBorg.ko_kr.json';
import Nechronica_ja_jp from 'bcdice/lib/bcdice/i18n/Nechronica.ja_jp.json';
import Nechronica_ko_kr from 'bcdice/lib/bcdice/i18n/Nechronica.ko_kr.json';
import NegikureNegimaki_ja_jp from 'bcdice/lib/bcdice/i18n/NegikureNegimaki.ja_jp.json';
import NegikureNegimaki_ko_kr from 'bcdice/lib/bcdice/i18n/NegikureNegimaki.ko_kr.json';
import NinjaSlayer2_ja_jp from 'bcdice/lib/bcdice/i18n/NinjaSlayer2.ja_jp.json';
import Nuekagami_ja_jp from 'bcdice/lib/bcdice/i18n/Nuekagami.ja_jp.json';
import Nuekagami_ko_kr from 'bcdice/lib/bcdice/i18n/Nuekagami.ko_kr.json';
import Revulture_ja_jp from 'bcdice/lib/bcdice/i18n/Revulture.ja_jp.json';
import Revulture_ko_kr from 'bcdice/lib/bcdice/i18n/Revulture.ko_kr.json';
import ShinobiGami_ja_jp from 'bcdice/lib/bcdice/i18n/ShinobiGami.ja_jp.json';
import ShinobiGami_ko_kr from 'bcdice/lib/bcdice/i18n/ShinobiGami.ko_kr.json';
import SkynautsBouken_ja_jp from 'bcdice/lib/bcdice/i18n/SkynautsBouken.ja_jp.json';
import SkynautsBouken_ko_kr from 'bcdice/lib/bcdice/i18n/SkynautsBouken.ko_kr.json';
import SRS_ja_jp from 'bcdice/lib/bcdice/i18n/SRS.ja_jp.json';
import SRS_ko_kr from 'bcdice/lib/bcdice/i18n/SRS.ko_kr.json';
import StarryDolls_ja_jp from 'bcdice/lib/bcdice/i18n/StarryDolls.ja_jp.json';
import StarryDolls_ko_kr from 'bcdice/lib/bcdice/i18n/StarryDolls.ko_kr.json';
import StellarKnights_ja_jp from 'bcdice/lib/bcdice/i18n/StellarKnights.ja_jp.json';
import StellarKnights_ko_kr from 'bcdice/lib/bcdice/i18n/StellarKnights.ko_kr.json';
import StratoShout_ja_jp from 'bcdice/lib/bcdice/i18n/StratoShout.ja_jp.json';
import StratoShout_ko_kr from 'bcdice/lib/bcdice/i18n/StratoShout.ko_kr.json';
import SwordWorld_ja_jp from 'bcdice/lib/bcdice/i18n/SwordWorld.ja_jp.json';
import SwordWorld_zh_hans from 'bcdice/lib/bcdice/i18n/SwordWorld.zh_hans.json';
import SwordWorld2_0_ja_jp from 'bcdice/lib/bcdice/i18n/SwordWorld2_0.ja_jp.json';
import SwordWorld2_0_zh_hans from 'bcdice/lib/bcdice/i18n/SwordWorld2_0.zh_hans.json';
import SwordWorld2_5_ja_jp from 'bcdice/lib/bcdice/i18n/SwordWorld2_5.ja_jp.json';
import SwordWorld2_5_zh_hans from 'bcdice/lib/bcdice/i18n/SwordWorld2_5.zh_hans.json';
import TensaiGunshiNiNaro_ja_jp from 'bcdice/lib/bcdice/i18n/TensaiGunshiNiNaro.ja_jp.json';
import UnsungDuet_ja_jp from 'bcdice/lib/bcdice/i18n/UnsungDuet.ja_jp.json';
import UnsungDuet_ko_kr from 'bcdice/lib/bcdice/i18n/UnsungDuet.ko_kr.json';
import Ventangle_ja_jp from 'bcdice/lib/bcdice/i18n/Ventangle.ja_jp.json';
import Ventangle_ko_kr from 'bcdice/lib/bcdice/i18n/Ventangle.ko_kr.json';
import YearZeroEngine_ja_jp from 'bcdice/lib/bcdice/i18n/YearZeroEngine.ja_jp.json';
import YearZeroEngine_ko_kr from 'bcdice/lib/bcdice/i18n/YearZeroEngine.ko_kr.json';
import ZombiLine_ja_jp from 'bcdice/lib/bcdice/i18n/ZombiLine.ja_jp.json';
import ZombiLine_ko_kr from 'bcdice/lib/bcdice/i18n/ZombiLine.ko_kr.json';

export const BCDICE_I18N_TRANSLATIONS: readonly object[] = [
  Airgetlamh_ja_jp,
  Airgetlamh_ko_kr,
  Alsetto_ja_jp,
  Alsetto_ko_kr,
  Amadeus_ja_jp,
  Amadeus_ko_kr,
  AnimaAnimus_ja_jp,
  AnimaAnimus_ko_kr,
  Arianrhod_ja_jp,
  Arianrhod_ko_kr,
  BeginningIdol_ja_jp,
  BeginningIdol_ko_kr,
  BlackJacket_ja_jp,
  BlackJacket_ko_kr,
  Bloodorium_ja_jp,
  Bloodorium_ko_kr,
  Cthulhu_en_us,
  Cthulhu_ja_jp,
  Cthulhu_ko_kr,
  Cthulhu_zh_hans,
  Cthulhu_zh_hant,
  CyberpunkRed_ja_jp,
  CyberpunkRed_ko_kr,
  DetatokoSaga_ja_jp,
  DetatokoSaga_ko_kr,
  DoubleCross_ja_jp,
  DoubleCross_ko_kr,
  Dracurouge_ja_jp,
  Dracurouge_ko_kr,
  Emoklore_ja_jp,
  Emoklore_ko_kr,
  Fiasco_ja_jp,
  Fiasco_ko_kr,
  FinalFantasyXIV_en_us,
  FinalFantasyXIV_ja_jp,
  FutariSousa_ja_jp,
  FutariSousa_ko_kr,
  HatsuneMiku_ja_jp,
  HatsuneMiku_ko_kr,
  Insane_ja_jp,
  Insane_ko_kr,
  Irisbane_ja_jp,
  Irisbane_ko_kr,
  JuinKansen_ja_jp,
  JuinKansen_ko_kr,
  Kamigakari_ja_jp,
  Kamigakari_ko_kr,
  KemonoNoMori_ja_jp,
  KemonoNoMori_ko_kr,
  KillDeathBusiness_ja_jp,
  KillDeathBusiness_ko_kr,
  KizunaBullet_ja_jp,
  KizunaBullet_ko_kr,
  LogHorizon_ja_jp,
  LogHorizon_ko_kr,
  MagicaLogia_ja_jp,
  MagicaLogia_ko_kr,
  MagicaLogia_zh_hans,
  MagicPunk_ja_jp,
  MagicPunk_ko_kr,
  MonotoneMuseum_ja_jp,
  MonotoneMuseum_ko_kr,
  MorkBorg_ja_jp,
  MorkBorg_ko_kr,
  Nechronica_ja_jp,
  Nechronica_ko_kr,
  NegikureNegimaki_ja_jp,
  NegikureNegimaki_ko_kr,
  NinjaSlayer2_ja_jp,
  Nuekagami_ja_jp,
  Nuekagami_ko_kr,
  Revulture_ja_jp,
  Revulture_ko_kr,
  ShinobiGami_ja_jp,
  ShinobiGami_ko_kr,
  SkynautsBouken_ja_jp,
  SkynautsBouken_ko_kr,
  SRS_ja_jp,
  SRS_ko_kr,
  StarryDolls_ja_jp,
  StarryDolls_ko_kr,
  StellarKnights_ja_jp,
  StellarKnights_ko_kr,
  StratoShout_ja_jp,
  StratoShout_ko_kr,
  SwordWorld_ja_jp,
  SwordWorld_zh_hans,
  SwordWorld2_0_ja_jp,
  SwordWorld2_0_zh_hans,
  SwordWorld2_5_ja_jp,
  SwordWorld2_5_zh_hans,
  TensaiGunshiNiNaro_ja_jp,
  UnsungDuet_ja_jp,
  UnsungDuet_ko_kr,
  Ventangle_ja_jp,
  Ventangle_ko_kr,
  YearZeroEngine_ja_jp,
  YearZeroEngine_ko_kr,
  ZombiLine_ja_jp,
  ZombiLine_ko_kr,
];
